### ISSUE TITLE
java.lang.VerifyError: Bad <init> method call from after the start of a try block

### ISSUE THREAD

**Issue by mgurmendez** [kaiwinter/dummyjdbc#5]
@kaiwinter, great library! thanks for this.

Facing a tricky issue, I think it might be related to: https://bugs.eclipse.org/bugs/show_bug.cgi?id=443477

![image](https://user-images.githubusercontent.com/2067736/37526955-30765cf6-2907-11e8-9d80-5d29cbf0556e.png)

I'm using dummyjdbc v1.3.0 any insights? 

Doesn't happen on my Mac but happens on Linux with java version jdk1.8.0_20

**Comment by kaiwinter** [comment]
Seems as the `aspectj-maven-plugin` which dummyjdbc uses is too old. Could you try updating it from 1.7 to 1.11?

Or could you provide a test case which enables me to reproduce this?
