### ISSUE TITLE
SELECT with WHERE clause

### ISSUE THREAD

**Issue by davidmichaelhuber** [kaiwinter/dummyjdbc#7]
Hi everybody!

I am trying to find out if I can use ```dummyjdbc``` for my use case in a JUnit test environment.

The thing is I am going to have a statement like ```SELECT * FROM table WHERE id = 1``` or also some statements that are going to use ```INNER JOIN```.

Did I understand the approach of ```dummyjdbc```wrong and those queries are not being interpreted correctly? I did a quick test and found out that ```SELECT * FROM table WHERE id = 1``` just returns the whole table.

Did I understand the concept wrong a little meaning that clauses, joins and so on are not supported? If that is not the case which SQL syntax is getting used?

**Comment by kaiwinter** [comment]
dummyjdbc does not fit your use case I´m afraid. The only part which is considered is the `FROM table` part. The whole content of a csv file with the name `table` is returned without restricting it by any `WHERE` condition. `JOIN`s are completely out of focus.

What may work for you is to register in each unit test a "special" csv file which contains the data your test should use: `DummyJdbcDriver.addTableResource("users", new File("user-with-id-1.csv"));`

**Comment by davidmichaelhuber** [comment]
That's very unfortunate to hear but thanks for the clarification though!

Thank you so much also for your suggested workaround! Just to get it right, in case of such a "special" csv file I will run into problems when I am testing a method that actually sets off two different SQL queries to the same table right? Let's say ```SELECT * FROM table WHERE ID = 1``` and ```SELECT * FROM table WHERE ID = 2```, both will return the same contents of the csv file defined for "table".

**Comment by kaiwinter** [comment]
> Let's say `SELECT * FROM table WHERE ID = 1` and `SELECT * FROM table WHERE ID = 2`, both will return the same contents of the csv file defined for "table", right?

That's correct.

**Comment by davidmichaelhuber** [comment]
Perfect! Thanks a lot for your help!
